const PROVIDER_REGISTRY = {
  community_alert_sos: {
    id: 'community_alert_sos',
    primaryProvider: 'alert-telemetry',
    fallbackProvider: null,
    coverage: 'global',
    updateCadence: '5-15s',
    latencyBudgetMs: 450,
    trustTier: 'A',
    sourceClass: 'internal_alert',
    sourceAuthority: 0.9,
    licenseNotes: 'Internal Alert telemetry (opt-in only).',
    adapterName: 'communityAdapter',
    rateLimitPolicy: '120 req/min per IP',
    cacheTTLms: 12_000,
    supportedEventTypes: ['sos'],
  },
  health_who: {
    id: 'health_who',
    primaryProvider: 'who',
    fallbackProvider: 'national-health-authorities',
    coverage: 'global',
    updateCadence: '12-24h',
    latencyBudgetMs: 1_600,
    trustTier: 'A',
    sourceClass: 'official',
    sourceAuthority: 1,
    licenseNotes: 'WHO public dashboard terms apply.',
    adapterName: 'healthAdapter',
    rateLimitPolicy: '30 req/min per IP',
    cacheTTLms: 30 * 60 * 1000,
    supportedEventTypes: ['pandemic', 'epidemic'],
  },
  geophysical_usgs: {
    id: 'geophysical_usgs',
    primaryProvider: 'usgs',
    fallbackProvider: 'gdacs',
    coverage: 'global',
    updateCadence: '1-5m',
    latencyBudgetMs: 1_100,
    trustTier: 'A',
    sourceClass: 'official',
    sourceAuthority: 0.98,
    licenseNotes: 'USGS Earthquake Hazards Program feed.',
    adapterName: 'geophysicalAdapter',
    rateLimitPolicy: '60 req/min per IP',
    cacheTTLms: 120_000,
    supportedEventTypes: ['earthquake'],
  },
  meteo_nowcast_openmeteo: {
    id: 'meteo_nowcast_openmeteo',
    primaryProvider: 'open-meteo-nowcast',
    fallbackProvider: 'gdacs',
    coverage: 'local-nowcast',
    updateCadence: '1-15m',
    latencyBudgetMs: 900,
    trustTier: 'B',
    sourceClass: 'verified_partner',
    sourceAuthority: 0.9,
    licenseNotes: 'Open-Meteo nowcast/forecast public API.',
    adapterName: 'meteoNowcastAdapter',
    rateLimitPolicy: '60 req/min per IP',
    cacheTTLms: 2 * 60 * 1000,
    supportedEventTypes: ['flood', 'storm', 'snowstorm', 'lightning', 'hail'],
  },
  hydro_gdacs: {
    id: 'hydro_gdacs',
    primaryProvider: 'gdacs',
    fallbackProvider: null,
    coverage: 'global',
    updateCadence: '5-30m',
    latencyBudgetMs: 1_300,
    trustTier: 'B',
    sourceClass: 'verified_partner',
    sourceAuthority: 0.82,
    licenseNotes: 'GDACS public feed (aggregated).',
    adapterName: 'meteoGdacsAdapter',
    rateLimitPolicy: '50 req/min per IP',
    cacheTTLms: 8 * 60 * 1000,
    supportedEventTypes: [
      'flood',
      'cyclone',
      'hurricane',
      'storm',
      'wildfire',
      'volcano',
      'tsunami',
      'drought',
      'high_tide',
      'rogue_waves',
      'sandstorm',
      'dust_devils',
      'downdraft',
      'heatwave',
      'snowstorm',
      'lightning',
      'hail',
      'wind_gust_10',
      'wind_gust_50',
    ],
  },
  infra_outages: {
    id: 'infra_outages',
    primaryProvider: 'utilities-open-data',
    fallbackProvider: 'validated-crowd',
    coverage: 'country-specific',
    updateCadence: '5-180m',
    latencyBudgetMs: 1_400,
    trustTier: 'B',
    sourceClass: 'verified_partner',
    sourceAuthority: 0.78,
    licenseNotes: 'Depends on local utility APIs per jurisdiction.',
    adapterName: 'infrastructureAdapter',
    rateLimitPolicy: '40 req/min per IP',
    cacheTTLms: 15 * 60 * 1000,
    supportedEventTypes: ['energy_outage', 'water_outage'],
  },
};

const EVENT_TYPE_TO_PROVIDER_IDS = {
  sos: ['community_alert_sos'],
  pandemic: ['health_who'],
  epidemic: ['health_who'],
  earthquake: ['geophysical_usgs'],
  flood: ['meteo_nowcast_openmeteo', 'hydro_gdacs'],
  cyclone: ['hydro_gdacs'],
  hurricane: ['hydro_gdacs'],
  storm: ['meteo_nowcast_openmeteo', 'hydro_gdacs'],
  wildfire: ['hydro_gdacs'],
  volcano: ['hydro_gdacs'],
  volcanic_cloud: ['hydro_gdacs'],
  tsunami: ['hydro_gdacs'],
  drought: ['hydro_gdacs'],
  high_tide: ['hydro_gdacs'],
  rogue_waves: ['hydro_gdacs'],
  sandstorm: ['hydro_gdacs'],
  dust_devils: ['hydro_gdacs'],
  downdraft: ['hydro_gdacs'],
  heat: ['hydro_gdacs'],
  heatwave: ['hydro_gdacs'],
  snowstorm: ['meteo_nowcast_openmeteo', 'hydro_gdacs'],
  lightning: ['meteo_nowcast_openmeteo', 'hydro_gdacs'],
  hail: ['meteo_nowcast_openmeteo', 'hydro_gdacs'],
  gale: ['hydro_gdacs'],
  wind: ['hydro_gdacs'],
  wind_gust_10: ['hydro_gdacs'],
  wind_gust_50: ['hydro_gdacs'],
  energy_outage: ['infra_outages'],
  water_outage: ['infra_outages'],
};

const PANDEMIC_WATCHLIST = [
  { id: 'novel_coronavirus', label: 'novel coronavirus', tags: ['covid', 'sars', 'mers'] },
  { id: 'influenza_a', label: 'influenza A', tags: ['influenza', 'h5', 'h7'] },
  { id: 'orthopoxvirus', label: 'orthopoxvirus', tags: ['mpox', 'orthopox'] },
  { id: 'filovirus', label: 'filovirus', tags: ['ebola', 'marburg'] },
  { id: 'henipavirus', label: 'henipavirus', tags: ['nipah', 'hendra'] },
];

module.exports = {
  PROVIDER_REGISTRY,
  EVENT_TYPE_TO_PROVIDER_IDS,
  PANDEMIC_WATCHLIST,
};
